everything:
  my_url: https://newsapi.org/v2/everything
  apikey: 20a0c464f00841a2b4019d426e96948a
  everything_headers:
    - Author Name
    - Title
    - Publish Date
headlines:
  my_url: https://newsapi.org/v2/top-headlines
  apikey: 20a0c464f00841a2b4019d426e96948a
  headlines_headers:
    - Author Name
    - Title
    - Publish Date
  search_indict:
    - None
    - title
    - discription
    - content


